variables:
  DOCKER_DRIVER: overlay2
  GIT_SSL_NO_VERIFY: "1"


stages:
  - build


build:
  image: google/cloud-sdk:latest
  stage: build
  retry: 2
  allow_failure: false
  script:
    - set -euxo pipefail
    - bash build-all.sh
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - bash push-all.sh

