variables:
  DOCKER_DRIVER: overlay2
  GIT_SSL_NO_VERIFY: "1"


stages:
  - build
  - push


build:
  image: google/cloud-sdk:latest
  stage: build
  retry: 2
  allow_failure: false
  tags:
    - radut-docker-ci
  script:
    - set -euxo pipefail
    - bash build-all.sh


push:
  image: google/cloud-sdk:latest
  stage: push
  when: manual
  retry: 2
  allow_failure: false
  tags:
    - radut-docker-ci
  script:
    - set -euxo pipefail
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - bash push-all.sh
