variables:
  DOCKER_DRIVER: overlay2
  GIT_SSL_NO_VERIFY: "1"


stages:
  - build
  - step1
  - step2
  - step3


ubuntu:
  image: google/cloud-sdk:latest
  stage: build
  artifacts: {}
  allow_failure: false
  script:
    - pushd ubuntu
    - bash build.sh
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - bash push.sh
    - popd

terraform-ansible:
  image: google/cloud-sdk:latest
  stage: build
  artifacts: {}
  allow_failure: true
  script:
    - pushd terraform-ansible
    - bash build.sh
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - bash push.sh
    - popd

varnish:
  image: google/cloud-sdk:latest
  stage: step1
  artifacts: {}
  allow_failure: false
  script:
    - pushd varnish
    - bash build.sh
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - bash push.sh
    - popd

openjdk-8:
  image: google/cloud-sdk:latest
  stage: step1
  artifacts: {}
  allow_failure: false
  script:
    - pushd openjdk-8
    - bash build.sh
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - bash push.sh
    - popd

openjdk-11:
  image: google/cloud-sdk:latest
  stage: step1
  artifacts: {}
  allow_failure: false
  script:
    - pushd openjdk-11
    - bash build.sh
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - bash push.sh
    - popd

openjdk-12:
  image: google/cloud-sdk:latest
  stage: step1
  artifacts: {}
  allow_failure: true
  script:
    - pushd openjdk-12
    - bash build.sh
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - bash push.sh
    - popd

openjdk-13:
  image: google/cloud-sdk:latest
  stage: step1
  artifacts: {}
  allow_failure: true
  script:
    - pushd openjdk-13
    - bash build.sh
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - bash push.sh
    - popd

#oracle-jdk8:
#  image: google/cloud-sdk:latest
#  stage: step1
#  artifacts: {}
#  allow_failure: true
#  script:
#    - pushd oracle-jdk8
#    - bash build.sh
#    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
#    - bash push.sh
#    - popd

openjdk-8-maven:
  image: google/cloud-sdk:latest
  stage: step2
  artifacts: {}
  allow_failure: false
  script:
    - pushd openjdk-8-maven
    - bash build.sh
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - bash push.sh
    - popd

openjdk-11-maven:
  image: google/cloud-sdk:latest
  stage: step2
  artifacts: {}
  allow_failure: false
  script:
    - pushd openjdk-11-maven
    - bash build.sh
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - bash push.sh
    - popd

openjdk-12-maven:
  image: google/cloud-sdk:latest
  stage: step2
  artifacts: {}
  allow_failure: true
  script:
    - pushd openjdk-12-maven
    - bash build.sh
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - bash push.sh
    - popd

openjdk-13-maven:
  image: google/cloud-sdk:latest
  stage: step2
  artifacts: {}
  allow_failure: true
  script:
    - pushd openjdk-13-maven
    - bash build.sh
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - bash push.sh
    - popd

#oracle-jdk8-maven:
#  image: google/cloud-sdk:latest
#  stage: step2
#  artifacts: {}
#  allow_failure: true
#  script:
#    - pushd oracle-jdk8-maven
#    - bash build.sh
#    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
#    - bash push.sh
#    - popd

openjdk-8-maven-nodejs:
  image: google/cloud-sdk:latest
  stage: step3
  artifacts: {}
  allow_failure: false
  script:
    - pushd openjdk-8-maven-nodejs
    - bash build.sh
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - bash push.sh
    - popd

openjdk-11-maven-nodejs:
  image: google/cloud-sdk:latest
  stage: step3
  artifacts: {}
  allow_failure: false
  script:
    - pushd openjdk-11-maven-nodejs
    - bash build.sh
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - bash push.sh
    - popd

openjdk-12-maven-nodejs:
  image: google/cloud-sdk:latest
  stage: step3
  artifacts: {}
  allow_failure: true
  script:
    - pushd openjdk-12-maven-nodejs
    - bash build.sh
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - bash push.sh
    - popd

openjdk-13-maven-nodejs:
  image: google/cloud-sdk:latest
  stage: step3
  artifacts: {}
  allow_failure: true
  script:
    - pushd openjdk-13-maven-nodejs
    - bash build.sh
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - bash push.sh
    - popd

#oracle-jdk8-maven-nodejs:
#  image: google/cloud-sdk:latest
#  stage: step3
#  artifacts: {}
#  allow_failure: true
#  script:
#    - pushd oracle-jdk8-maven-nodejs
#    - bash build.sh
#    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
#    - bash push.sh
#    - popd
